# Generated by Django 3.0.7 on 2020-07-01 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import oauth.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Application Name')),
                ('client_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Client ID')),
                ('client_secret', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Client Secret')),
                ('type', models.CharField(choices=[('client', 'Client App'), ('service', 'Web Service')], help_text='The type of application this is', max_length=16, verbose_name='Type')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=oauth.models.generate_token, max_length=255, verbose_name='Token')),
                ('expiration', models.DateTimeField(default=oauth.models.refresh_token_expiration_time, verbose_name='Expiration')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='oauth.Application', verbose_name='Application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=oauth.models.generate_token, max_length=255, verbose_name='Token')),
                ('expiration', models.DateTimeField(default=oauth.models.access_token_expiration_time, verbose_name='Expiration')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='oauth.Application', verbose_name='Application')),
                ('refresh_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='oauth.RefreshToken', verbose_name='Refresh Token')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
